export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE";

export const SAVE_NOTE = "SAVE_NOTE";
export const SAVE_NOTE_SUCCESS = "SAVE_NOTE_SUCCESS";
export const SAVE_NOTE_FAILURE = "SAVE_NOTE_FAILURE";

export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";

export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_FOREVER = "DELETE_NOTE_FOREVER";
export const RESTORE_NOTE = "RESTORE_NOTE";

export const CHANGE_NOTE_BG_COLOR = "CHANGE_NOTE_BG_COLOR";
export const UPDATE_NOTE_CONTENT = "UPDATE_NOTE_CONTENT";